# Generated by Django 5.0.6 on 2024-09-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(max_length=30)),
                ('fecha', models.DateField(verbose_name='Fecha de Envio')),
                ('enviado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('ciudad', models.CharField(blank=True, max_length=30, null=True)),
                ('celular', models.BigIntegerField()),
            ],
        ),
    ]
