# Generated by Django 5.0.6 on 2024-09-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviado',
            name='enviado',
            field=models.BooleanField(verbose_name='Entregado'),
        ),
    ]
